trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: test
    type: boolean
    default: false
  - name: test1
    type: boolean
    default: false
  - name: test2
    type: boolean
    default: false
  - name: test3
    type: boolean
    default: false

variables:
  - name: connectionlist
    value: >-
      test
      test1
      test2
      test3

jobs:
  - ${{ each connection in concat(
      parameters.test  == true  ? join(['test'], '')  : join([], ''),
      parameters.test1 == true  ? join(['test1'], '') : join([], ''),
      parameters.test2 == true  ? join(['test2'], '') : join([], ''),
      parameters.test3 == true  ? join(['test3'], '') : join([], '')
    ) }}:
      - job: Job_${{ connection }}
        condition: eq(${{ parameters.connection }}, true)
        steps:
          - template: ./test.yml
            parameters:
              connection: ${{ connection }}
