trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: connections
    value: "test,test,test,test,test"
  - name: connectionlist
    value: >
      test
      test
      test
      test

steps:
  - ${{ each connection in split(variables.connectionlist, ' ')}}:
      - template: ./test.yml
        parameters:
          connection: ${{ connection }}
