trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: connectionlist
    value: >-
      test
      test1
      test2
      test3

jobs:
  - ${{ each connection in split(variables.connectionlist, ' ')}}:
      - job: Job_${{ connection }}
        steps:
          - template: ./test.yml
            parameters:
              connection: ${{ connection }}
