trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: connectionlist
    value: >-
      test
      test1
      test2
      test3

steps:
  - ${{ each connection in split(variables.connectionlist, ' ')}}:
      - template: ./test.yml
        parameters:
          connection: ${{ connection }}
