trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: test
    type: boolean
    default: false
  - name: test1
    type: boolean
    default: false
  - name: test2
    type: boolean
    default: false
  - name: test3
    type: boolean
    default: false

variables:
  - group: VARIABLES_VALUES
  - name: connectionlist
    value: >-
      test
      test1
      test2
      test3
  - name: test
    value: TEST_VAR
  - name: test1
    value: TEST1_VAR
  - name: test2
    value: TEST2_VAR
  - name: test3
    value: TEST3_VAR

jobs:
  - ${{ each connection in split(variables.connectionlist, ' ')}}:
      - job: Job_${{ connection }}
        condition: eq(${{ parameters[connection] }}, true)
        variables:
          - group: ${{ variables[connection] }}
          - ${{ if or(eq(connection, 'test'), eq(connection, 'test2')) }}:
              - name: v2Check
                value: "true"
          - ${{ else }}:
              - name: v2Check
                value: "false"
        steps:
          - template: ./test.yml
            parameters:
              connection: ${{ connection }}
