trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: test
    type: boolean
    default: false
  - name: test1
    type: boolean
    default: false
  - name: test2
    type: boolean
    default: false
  - name: test3
    type: boolean
    default: false

variables:
  - group: VARIABLES_VALUES
  - name: connectionlist
    value: >-
      test
      test1
      test2
      test3

jobs:
  - ${{ each connection in split(variables.connectionlist, ' ')}}:
      - job: Job_${{ connection }}
        condition: eq(${{ parameters[connection] }}, true)
        variables:
          - group: $(${{ connection }})
        steps:
          - template: ./test.yml
            parameters:
              connection: ${{ connection }}
